# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b0be6a07af91744bd79f2b40529cd2e25a41576812eeae58334ddddee7b9762e57b0621aa2f6db46dd25cb60cdf42703882a02c9146840671a7fd33a0b1e08

test:
  secret_key_base: 83be782d15281439b6af93db85d07fa6bf89782582a430d7bb0c81e6660296f54620e30e43bc304bbd525420e6fce7b8b53c17ef9c4d721fcfde849081ded930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
